### ISSUE TITLE
Project don't build

### ISSUE THREAD

**Issue by hannesa2** [spokestack/app-actions-example#1]
https://github.com/spokestack/app-actions-example/blob/ee06c22a13fea686c893dfa1383ad2645747eb0d/app/src/main/java/io/spokestack/actions/Voice.kt#L76

<img width="390" alt="image" src="https://user-images.githubusercontent.com/3314607/115025999-44cc0f00-9ec2-11eb-86d5-5acbac69b945.png">

I guess, you need a CI

**Comment by hannesa2** [comment]
Please see CI pull request #3

**Comment by hannesa2** [comment]
Please see quick build fix #4

**Comment by hannesa2** [comment]
close #4

**Comment by hannesa2** [comment]
To continue with my evaluation, please see https://forum.spokestack.io/c/spokestack-libraries/10
Btw, I like to search for help here in Github more then an additional forum

**Comment by space-pope** [comment]
The questions you posted in that forum are related to your Spokestack account, not any library or sample code repository, so there's unfortunately not a great place to address them on GitHub.
